alias: Awtrix Schlafmodus Steuerung
description: Schaltet Awtrix Schlafmodus je nach Uhrzeit um
triggers:
  - at: "06:00:00"
    trigger: time
  - at: "21:00:00"
    trigger: time
conditions: []
actions:
  - choose:
      - conditions:
          - condition: time
            after: "06:00:00"
            before: "20:00:00"
        sequence:
          - data: {}
            action: script.awtrix_sleep_off
      - conditions:
          - condition: time
            after: "21:00:00"
            before: "06:00:00"
        sequence:
          - data: {}
            action: script.awtrix_sleep_on
mode: single
