alias: Gute Luft
description: ""
triggers:
  - entity_id: binary_sensor.lumi_lumi_sensor_motion_bewegung
    to: "on"
    trigger: state
  - entity_id: sensor.meter_65b9_kohlendioxid
    above: 0
    below: 1500
    trigger: numeric_state
conditions:
  - condition: and
    conditions:
      - condition: time
        after: "06:00:00"
        before: "21:00:00"
      - condition: state
        entity_id: binary_sensor.lumi_lumi_sensor_motion_belegung
        state: "on"
      - condition: numeric_state
        entity_id: sensor.meter_65b9_kohlendioxid
        above: 0
        below: 1500
actions:
  - data:
      icon: 33139
      rainbow: false
      lifetime: 0
      duration: 15
      textcase: 0
      topicname: CO2_Good
      text: >-
        Es braucht nicht gelüftet werden, beim Wert {{
        states('sensor.meter_65b9_kohlendioxid') | round(0) }} ppm.  
    action: script.awtrix_new_notify
mode: single
